- project:
    templates:
      - openstack-lower-constraints-jobs-neutron
      - openstack-python-jobs-neutron
      - publish-openstack-docs-pti
      - openstack-python35-jobs-neutron
      - openstack-python36-jobs-neutron
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-lower-constraints:
            required-projects:
              - openstack/neutron-lib
              - openstack/networking-bgpvpn
        - openstack-tox-pep8:
            required-projects:
              - openstack/neutron-lib
              - openstack/networking-bgpvpn
        - openstack-tox-py27:
            required-projects:
              - openstack/neutron-lib
              - openstack/networking-bgpvpn
        - openstack-tox-py35:
            required-projects:
              - openstack/neutron-lib
              - openstack/networking-bgpvpn
        - openstack-tox-py36:
            required-projects:
              - openstack/neutron-lib
              - openstack/networking-bgpvpn
    gate:
      jobs:
        - openstack-tox-lower-constraints:
            required-projects:
              - openstack/neutron-lib
              - openstack/networking-bgpvpn
        - openstack-tox-pep8:
            required-projects:
              - openstack/neutron-lib
              - openstack/networking-bgpvpn
        - openstack-tox-py27:
            required-projects:
              - openstack/neutron-lib
              - openstack/networking-bgpvpn
        - openstack-tox-py35:
            required-projects:
              - openstack/neutron-lib
              - openstack/networking-bgpvpn
        - openstack-tox-py36:
            required-projects:
              - openstack/neutron-lib
              - openstack/networking-bgpvpn