- project:
    templates:
      - openstack-lower-constraints-jobs-neutron
      - openstack-python-jobs-neutron
      - publish-openstack-docs-pti
      - openstack-python3-train-jobs-neutron
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-lower-constraints:
            required-projects:
              - openstack/neutron-lib
        - openstack-tox-pep8:
            required-projects:
              - openstack/neutron-lib
        - openstack-tox-py27:
            required-projects:
              - openstack/neutron-lib
        - openstack-tox-py36:
            required-projects:
              - openstack/neutron-lib
        - openstack-tox-py37:
            required-projects:
              - openstack/neutron-lib
    gate:
      jobs:
        - openstack-tox-lower-constraints:
            required-projects:
              - openstack/neutron-lib
        - openstack-tox-pep8:
            required-projects:
              - openstack/neutron-lib
        - openstack-tox-py27:
            required-projects:
              - openstack/neutron-lib
        - openstack-tox-py36:
            required-projects:
              - openstack/neutron-lib
        - openstack-tox-py37:
            required-projects:
              - openstack/neutron-lib
